<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<artifactId>pluginsib-barcode-pdf417</artifactId>
	<name>PluginsIB - BarCode - PDF417</name>
	<parent>
		<groupId>org.fundaciobit.pluginsib.barcode</groupId>
		<version>4.0.0-SNAPSHOT</version>
		<artifactId>pluginsib-barcode</artifactId>
	</parent>
	<dependencies>
		<dependency>
			<groupId>org.fundaciobit.pluginsib.barcode</groupId>
			<artifactId>pluginsib-barcode-api</artifactId>
			<version>${project.version}</version>
		</dependency>
	</dependencies>
</project>
